### ISSUE TITLE
exporter is rotating uvs 180 degrees in some cases

### ISSUE THREAD

**Issue by xackery** [xackery/quail#6]
![image](https://github.com/xackery/quail/assets/845670/4d79cb0e-41e8-44c4-ab6e-9d4c4ecc088f)
![image](https://github.com/xackery/quail/assets/845670/ae27c905-1086-4dda-ae15-3fc41e46a0e5)

**Comment by DeadZergling** [comment]
Just making note that this seems an issue with eqgzi as well, not just quail, as a reminder when you start bug squashing.

**Comment by xackery** [comment]
This likely won't be applicable anymore as we expand the intermediary format
