### ISSUE TITLE
4 objects in a collection export improperly

### ISSUE THREAD

**Issue by xackery** [xackery/quail#7]
![image](https://github.com/xackery/quail/assets/845670/3cec80ee-039c-4c28-a4c0-12ddc8d61e7b)

from https://discord.com/channels/212663220849213441/924818607303716956/1153253085301440583

**Comment by DeadZergling** [comment]
[rudelittleimpweapons2weapbackuppacked.zip](https://github.com/xackery/quail/files/12653746/rudelittleimpweapons2weapbackuppacked.zip)
Here it is, hopefully, did the packing thing as well.

**Comment by xackery** [comment]
This likely isn't appliable anymore after our wce rewrite
