### ISSUE TITLE
Quail Might not be applying some shaders properly

### ISSUE THREAD

**Issue by DeadZergling** [xackery/quail#9]
![image](https://github.com/xackery/quail/assets/18122846/6c36b8f5-bced-4ca3-beac-68104b5b18f8)

Using a shader with custom properties of

String e_TextureNormal0  = "2 pinktongue_alb_n.dds"
String e_fShininess0 = "0 0"
String fx = "Opaque_MaxCBSG1.fx"

Doesn't work the same as it did for an object in a zone file.  Picture included, I used the shader, particularly the 0 0 shininess to remove any weird light irregularities in some objects, all be the same light level, but it clearly isn't working on that weapon.

[rudelittleimpweapons.zip](https://github.com/xackery/quail/files/12668898/rudelittleimpweapons.zip)

[rudelittleimpweaponsblend.zip](https://github.com/xackery/quail/files/12668905/rudelittleimpweaponsblend.zip)

I have included the EQG made and the associated blend file, can make a simple test zone with something with the property if that helps.

**Comment by xackery** [comment]
Going to close this as quail is doing an entire rewrite
